[phases.setup]
nixPkgs = ["dotnet-sdk_8", "icu", "openssl"]

[phases.install]
cmds = [
  "dotnet restore AIReception.Mvc.csproj"
]

[phases.build]
cmds = [
  "dotnet publish AIReception.Mvc.csproj -c Release -o out --no-restore"
]

[start]
cmd = "dotnet out/AIReception.Mvc.dll"
